### ISSUE TITLE
idk anymore

### ISSUE THREAD

**Issue by BambiGaming2022** [Joalor64GH/Joalor64-Engine-Rewrite#1]
modcharting/PlayfieldRenderer.hx (line 118)
PlayState.hx (line 418)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 550)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/Joalor64GH/Joalor64-Engine-Rewrite/issues

> Crash Handler written by: sqirra-rng

i found this bug over here and its says Null Object Reference
what to do
delete all OG weeks or keep it

**Comment by Joalor64GH** [comment]
were you trying to do something?

**Comment by BambiGaming2022** [comment]
Modding

**Comment by BambiGaming2022** [comment]
No

**Comment by BambiGaming2022** [comment]
yes its works
thank you
