### ISSUE TITLE
Issues I wanna point out

### ISSUE THREAD

**Issue by MemeHovy** [Joalor64GH/Joalor64-Engine-Rewrite#15]
This is a list of issues the engine has rn that may be fixed soon
* 1. Lua tweens being slow af (like seen with the results screen)

Fixed:
* Lose icons not working

See: #16

**Comment by Joalor64GH** [comment]
Just saying, i actually noticed the long sustain notes too

**Comment by MemeHovy** [comment]
yeah, I'mma try and fix this

**Comment by MemeHovy** [comment]
well I couldn't fix it, it could just be an issue with the note texture itself

**Comment by MemeHovy** [comment]
also I fixed the lose icons

**Comment by MemeHovy** [comment]
found out the sustains issue
