### ISSUE TITLE
Weird bug at last song (require pressing enter to end this) & Good judgement still MFC

### ISSUE THREAD

**Issue by RandomUserOnInternet** [Joalor64GH/Joalor64-Engine-Rewrite#22]
https://user-images.githubusercontent.com/105424534/233835688-d6295710-7c08-4efc-bb77-faa5a0cd4c29.mp4

Here's the bug in Video :(

**Comment by RandomUserOnInternet** [comment]
I realize now MFC = GFC but this is not make sense

**Comment by Joalor64GH** [comment]
i uhhh
i'll see what i can do
