### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by Hiho2950** [Joalor64GH/Joalor64-Engine-Rewrite#24]
when i enter a song (playstate), everything will be like not smooth like 20 fps or 10 but in the fps counter in the corner i have 60 fps but in the other states everything is normal.
i m trying to port this engine to android, so pls can you help me?

**Comment by MemeHovy** [comment]
likely an issue with your phone, and this engine wasn't really targeted towards android either

**Comment by Hiho2950** [comment]
> likely an issue with your phone, and this engine wasn't really targeted towards android either

no , it s not because i have fnf ported by MaysLastPlay77 and work smoothly

**Comment by MemeHovy** [comment]
oh, well point being this engine wasn't optimized for android, nor was it targeted towards android users

**Comment by Hiho2950** [comment]
> oh, well point being this engine wasn't optimized for android, nor was it targeted towards android users

ok i will try to optimize

**Comment by MemeHovy** [comment]
👍🏻

**Comment by Hiho2950** [comment]
> 👍🏻

i got just some problems with teascript and hscript files about teascript with class but the hscript i have try the zavodila.hscript who is in the data folder

**Comment by MemeHovy** [comment]
kid I can't help with android ports because I only have a emulator, and I can't compile android either sorry

**Comment by Hiho2950** [comment]
> kid I can't help with android ports because I only have a emulator, and I can't compile android either sorry

ok about that it can be fixed but about hscript idk about lua functions if imported or not

**Comment by Hiho2950** [comment]
> kid I can't help with android ports because I only have a emulator, and I can't compile android either sorry

Now it s fixed
