### ISSUE TITLE
the camera stuff works but...

### ISSUE THREAD

**Issue by Joalor64GH** [Joalor64GH/Joalor64-Engine-Rewrite#30]
we should probably get this fixed
![Friday Night Funkin'_ Joalor64 Engine Rewritten 7_6_2023 3_41_31 PM](https://github.com/Joalor64GH/Joalor64-Engine-Rewrite/assets/99079926/37b9e1b6-cad3-4a69-a382-ac4e5abcb1ff)

**Comment by MemeHovy** [comment]
eesh, yea we should

**Comment by Joalor64GH** [comment]
https://github.com/Joalor64GH/Joalor64-Engine-Rewrite/commit/22cf25176753b808b31a302d106c32c6d4ae7692

**Comment by RandomUserOnInternet** [comment]
@Joalor64GH Wait a minute... It has same function dude... 
![image](https://github.com/Joalor64GH/Joalor64-Engine-Rewrite/assets/105424534/e2bb3019-50e8-467c-adc6-b82951714742)
![image](https://github.com/Joalor64GH/Joalor64-Engine-Rewrite/assets/105424534/b2f9be85-bc4b-41b1-b467-5ea1df32e14e)

**Comment by Joalor64GH** [comment]
oh
