### ISSUE TITLE
Alphabet text on replay select screen it's weird, i mean position.

### ISSUE THREAD

**Issue by Stefan2008Git** [Joalor64GH/Joalor64-Engine-Rewrite#32]
What it this dude?
![slika](https://github.com/Joalor64GH/Joalor64-Engine-Rewrite/assets/126715034/33ddc9eb-d753-4cfb-99ba-7143638d23a2)

**Comment by Joalor64GH** [comment]
oh shoot that wasn't supposed to happen

**Comment by Joalor64GH** [comment]
i'm gonna fix that

**Comment by Stefan2008Git** [comment]
> oh shoot that wasn't supposed to happen

Yeah i see LOL
