### ISSUE TITLE
Oops

### ISSUE THREAD

**Issue by Joalor64GH** [Joalor64GH/Joalor64-Engine-Rewrite#39]
@moxie-coder When you can, can you help fix things please? I was just testing 1.4.0-rc1, and a TON of stuff broke. So, yeah. When you can.

**Comment by Joalor64GH** [comment]
i fixed the issue
but im triggered because SOMEHOW three lines of code broke the whole game :skull:

**Comment by moxie-coder** [comment]
> @moxie-coder When you can, can you help fix things please? I was just testing 1.4.0-rc1, and a TON of stuff broke. So, yeah. When you can.

oki
