### ISSUE TITLE
Two important issues (at the moment)

### ISSUE THREAD

**Issue by Joalor64GH** [Joalor64GH/Joalor64-Engine-Rewrite#40]
1. the game crashes when exiting PlayState
2. the game crashes upon entering ModchartEditorState

**Comment by Joalor64GH** [comment]
@GuineaPigUuhh do you think you could help on this please?

**Comment by GuineaPigUuhh** [comment]
👍 but I'll try to fix it on Thursday, because I don't have school that day

**Comment by GuineaPigUuhh** [comment]
unfortunately, I couldn't solve the bug.

**Comment by Joalor64GH** [comment]
oh

**Comment by Joalor64GH** [comment]
at least tell me, why am i getting an error on a blank line?
(PlayState line 5860)

**Comment by GuineaPigUuhh** [comment]
usually it's either the line above that has the error or the one below.

**Comment by Joalor64GH** [comment]
@moxie-coder when you're not busy, **please** do something about this
it's actually starting to annoy me

**Comment by moxie-coder** [comment]
> @moxie-coder when you're not busy, **please** do something about this it's actually starting to annoy me

I know I’m trying to, as you can tell but having a Low end ram pc isn’t helping

**Comment by Joalor64GH** [comment]
oh

**Comment by Joalor64GH** [comment]
@moxie-coder @GuineaPigUuhh PLAYSTATE ISSUE HAS BEEN FIXED!!
modchart editor is still crashing tho, but we can fix that later.

**Comment by moxie-coder** [comment]
> @moxie-coder @GuineaPigUuhh PLAYSTATE ISSUE HAS BEEN FIXED!! modchart editor is still crashing tho, but we can fix that later.

yeah I fixed the playstate issue
