### ISSUE TITLE
Error when trying to compile

### ISSUE THREAD

**Issue by PHGaming121** [Joalor64GH/Joalor64-Engine-Rewrite#6]
when i try to compile the engine, this happens:

source/WebmHandler.hx:32: characters 10-26 : Not enough arguments, expected io:webm.WebmIo, soundEnabled:Bool
source/WebmHandler.hx:33: characters 8-12 : webm.WebmPlayer has no field fuck
source/WebmHandler.hx:100: characters 8-21 : webm.WebmPlayer has no field changePlaying
source/WebmHandler.hx:106: characters 8-21 : webm.WebmPlayer has no field changePlaying
source/WebmHandler.hx:57: characters 8-12 : webm.WebmPlayer has no field fuck
source/WebmHandler.hx:125: characters 8-19 : webm.WebmPlayer has no field removePause

what is this aaaaaaaaaaaaaaaaaaaaaaaaaaahhhhhhhhhhhhhhhhh

**Comment by Joalor64GH** [comment]
did you install extension-webm from here?
https://github.com/KadeDev/extension-webm

**Comment by PHGaming121** [comment]
![Captura de Tela (127)](https://user-images.githubusercontent.com/76562427/216787923-d8e9261e-9685-4172-a342-4bbfb53763a3.png)

**Comment by PHGaming121** [comment]
this happens everytime i enter a song
